- name: Automatically create a new root ssh key
  action: command ssh-keygen -t rsa -N "" -f /root/.ssh/id_rsa creates=/root/.ssh/id_rsa

- name: Get the new public key for reuse 
  action: fetch src=/root/.ssh/id_rsa.pub dest=/tmp/controller.pub
