- hosts: chef-server
  user: root
  vars_files:
  - "vars/global_vars.yml"
  vars_prompt:
    - name: "openstack_admin_password"
      prompt: "Enter password for OpenStack admin user"
      private: yes
  tasks:
    - include: chef-server/tasks/packages.yml
    - include: chef-server/tasks/download_cookbooks.yml
    - include: chef-server/tasks/setup_knife.yml
