- hosts: openstack-nodes
  user: root
  vars_files:
  - "vars/config.yml"
  tasks:
    - include: common/tasks/ssh_keys.yml user=root
    - include: common/tasks/update.yml
    - include: common/tasks/add_ops_repo.yml
    - include: common/tasks/packages.yml
    - include: common/tasks/motd.yml
    - include: common/tasks/crashdump.yml
    - include: common/tasks/bootstrap_puppet.yml
    #- include: common/tasks/enable_hyperthreading.yml
    #- include: common/tasks/reboot.yml
    #- include: common/tasks/wait_for_boot.yml
