- hosts: controller
  user: root
  vars_files:
  - "vars/config.yml"
  tasks:
    - include: controller/tasks/packages.yml
    - include: controller/tasks/local_kvm.yml
    - include: controller/tasks/chef_server.yml
  handlers:
    - include: controller/handlers/restart_iptables.yml
