- hosts: compute
  user: root
  vars_files:
  - "vars/config.yml"
  vars:
    - host: $hostvars.{${groups.controller}[0]}.ansible_eth0
    - roles: "'role[single-compute]'"
  tasks:
    - include: common/tasks/run_chef.yml
