environment: dev99
puppetmaster: puppet-n01.staging.us.ccp.rackspace.net
repo_server: puppet-n01.staging.us.ccp.rackspace.net
chef_ip: 169.254.123.2
chef_path: /opt/rpcs
chef_cookbook_src: http
chef_cookbook_url: http://8a8313241d245d72fc52-b3448c2b169a7d986fbb3d4c6b88e559.r9.cf1.rackcdn.com/chef-cookbooks-v3.0.0.tgz
chef_cookbook_path: /opt/rpcs/chef-cookbooks-v3.0.0
chef_vm_url: http://c390813.r13.cf1.rackcdn.com/chef-server.qcow2
openstack_release: folsom
openstack_environment: dev99
dashboard_theme: Rackspace
default_store: swift
ram_ratio: 1.0
cpu_ratio: 2.0
autostart: false
resume_state: false
custom_banner: Integrating the Cloud
tenants:
  - integration
  - analytics
  - repose
  - atomhopper
glance_images:
  - cirros
  - precise
mgmt_ipv4_cidr: 10.127.36.0/24
mgmt_dev: eth0
networks:
  public:
    bridge: br0
    bridge_dev: eth1:0
    dns_server1: 72.3.128.240
    dns_server2: 72.3.128.241
    network_size: 254
    ipv4_cidr: 192.168.90.0/24
  protected:
    bridge: br1
    bridge_dev: eth1:1
    dns_server1: 72.3.128.240
    dns_server2: 72.3.128.241
    network_size: 254
    ipv4_cidr: 192.168.91.0/24
  private:
    bridge: br2
    bridge_dev: eth1:2
    dns_server1: 72.3.128.240
    dns_server2: 72.3.128.241
    network_size: 254
    ipv4_cidr: 192.168.92.0/24
