- name: Download latest chef rpm from opscode
  action: get_url url=http://www.opscode.com/chef/download?v=&prerelease=false&p=el&pv=6&m=x86_64 dest=/tmp/chef.rpm mode=0440

- name: Install chef
  action: yum install name=/tmp/chef.rpm

- name: Install git
  action: yum install name=git
