- name: Download latest chef rpm from opscode
  action: get_url url=http://www.opscode.com/chef/download?v=&prerelease=false&p=ubuntu&pv=12.04&m=x86_64 dest=/tmp/chef.deb mode=0440

- name: Install chef from local file
  action: apt pkg=/tmp/chef.deb state=installed
  tags:
    - packages