- name: Ensure chef config directory exists for root
  action: file path=/home/rack/.chef owner=rack group=rack mode=0755 state=directory

- name: Place knife config
  action: copy src=/etc/ansible/playbooks/openstack/chef-server/files/knife.rb dest=/home/rack/.chef/knife.rb owner=rack group=rack mode=0644

- name: Reregister $item
  action: command knife client reregister rack -f /home/rack/.chef/rack.pem creates=/home/rack/.chef/rack.pem

- name: Reregister $item
  action: command knife client reregister chef-validator -f /home/rack/.chef/chef-validator.pem creates=/home/rack/.chef/chef-validator.pem

- name: Delete existing controller client
  action: command knife client delete controller -y
  ignore_errors: yes

- name: Generate knife environment file
  action: template src=/etc/ansible/playbooks/openstack/chef-server/templates/knife-environment.json.j2 dest=/tmp/${openstack_environment}.json owner=rack group=rack mode=0644

- name: Create new environment
  action: command knife environment from file -d /tmp/${openstack_environment}.json

- name: Recreate knife client
  sudo: yes
  action: shell knife client create controller -d -a > /usr/share/chef-server-api/public/controller.pem creates=/usr/share/chef-server-api/public/controller.pem

- name: Grab the controller.pem
  action: fetch src=/usr/share/chef-server-api/public/controller.pem dest=/tmp/
